### ISSUE TITLE
Unable to reset password of any user.

### ISSUE THREAD

**Issue by vipinlalcm** [sii/siptrackd#11]
When we reset password of a user, we are getting following error.
"'tuple' object has no attribute 'isValidPassword'"
![image](https://user-images.githubusercontent.com/8621243/58413888-83227000-8097-11e9-965d-3572fc77060f.png)

![resetpassword](https://user-images.githubusercontent.com/8621243/58413772-3c347a80-8097-11e9-868a-9795e6211953.JPG)

**Comment by vipinlalcm** [comment]
Its duplicate issue of 
https://github.com/sii/siptrackd/issues/8

**Comment by lalusvipi** [comment]
Yes. You are correct. The following error triggered from [https://github.com/sii/siptrackd/blob/master/siptrackdlib/user.py#L690](url)

As per the current code, while resetting the password, it should disconnect all subkeys and trying to connect the subkeys with new password instead of old subkey and its actual password keys password.

However, as per my understanding. The current code does not allow to do so. Because, During the initial stage of development , @sii has designed this to reset all the subkeys and user password dependencies while resetting a users password. Because when a user required password reset when he has forgot the old password. Whereas if he knows the old password and still he need to change the password. He can use UpdatePassword utility in the User interface. That works fine.

Also, current web ui has already given a warning while resetting the password.
![image](https://user-images.githubusercontent.com/8621243/58415455-27a6b100-809c-11e9-9621-1e671db423a4.png)

As @stemid has updated it would work better if we can add subkeys without password keys password. But that will go against the current system logic. We have to redesign the applications password creation functions totally to achieve that. We can do it later.  But as a workaround we can apply the below code. Which will reset the password but user has to login with the new password and connect all the password keys manually.
#12 

This will delete all the subkeys and reset the password without error. But only think is it does not add any subkeys in to user. If user has any subkeys, it has to be reconnected manually.
